"use client";
import {preparePhoto} from "@/lib/prepare-photo";
import { useCallback, useEffect, useState, type FormEvent } from "react";
type Attachment = { id: string; name: string; url: string; mime_type: string; size_bytes: string };
export default function TripFiles({ tripId, canEdit, kind }: { tripId: string; canEdit: boolean; kind: "photo" | "document" }) {
 const [files,setFiles]=useState<Attachment[]>([]);const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);
 const endpoint=`/api/trips/${tripId}/files?kind=${kind}`;
 const load=useCallback(async()=>{try{const r=await fetch(endpoint);const data=await r.json();if(!r.ok)throw new Error();setFiles(data.files);}catch{setError("Não foi possível carregar os arquivos.");}finally{setLoading(false);}},[endpoint]);
 useEffect(()=>{void load();},[load]);
 async function upload(event: FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const data=new FormData(form);data.set("kind",kind);setBusy(true);setError("");try{const file=data.get("file");if(kind==="photo"&&file instanceof File)data.set("file",await preparePhoto(file));const r=await fetch(endpoint,{method:"POST",body:data});const result=await r.json();if(!r.ok)throw new Error(result.error);form.reset();await load();}catch(err){setError(err instanceof Error?err.message:"Falha no upload.");}finally{setBusy(false);}}
 async function remove(id:string){if(!confirm("Excluir este arquivo?"))return;setBusy(true);setError("");try{const r=await fetch(`${endpoint}&fileId=${id}`,{method:"DELETE"});if(!r.ok)throw new Error();await load();}catch{setError("Não foi possível excluir. Apenas o autor ou proprietário pode excluir o arquivo.");}finally{setBusy(false);}}
 return <section className="mt-5 rounded-3xl border bg-white p-5 sm:p-7"><h2 className="text-xl font-bold">{kind==="photo"?"Fotos da viagem":"Documentos privados"}</h2><p className="mt-2 text-sm text-neutral-500">Disponíveis somente para os participantes desta viagem. Até 4 MB por arquivo.</p>{error&&<p role="alert" className="mt-3 text-red-700">{error}</p>}{loading&&<p role="status">Carregando arquivos…</p>}
 {canEdit&&<form onSubmit={upload} className="my-4 flex flex-wrap gap-3"><input aria-label={kind==="photo"?"Selecionar foto":"Selecionar documento"} type="file" name="file" required accept={kind==="photo"?"image/jpeg,image/png,image/webp":"application/pdf,image/jpeg,image/png,image/webp"} className="max-w-full rounded-xl border p-2"/><button disabled={busy} className="rounded-xl bg-neutral-950 p-3 text-white">{busy?"Aguarde…":"Enviar arquivo"}</button></form>}
 {!loading&&!files.length&&<p className="my-4 text-neutral-500">Nenhum arquivo adicionado.</p>}<div className="grid gap-4 sm:grid-cols-3">{files.map(file=><article key={file.id} className="overflow-hidden rounded-xl border p-3">{kind==="photo"&&<img src={file.url} alt={file.name} loading="lazy" className="mb-3 aspect-video w-full rounded-lg object-cover"/>}<a href={file.url} target="_blank" rel="noreferrer" className="break-words font-medium underline">{file.name}</a>{canEdit&&<button disabled={busy} onClick={()=>void remove(file.id)} className="mt-2 block p-2 text-sm text-red-700">Excluir</button>}</article>)}</div></section>;
}
