"use client";
import {useState,type FormEvent} from "react";
export default function TripLifecycle({tripId,status,title,description,startDate,endDate}:{tripId:string;status:string;title:string;description:string|null;startDate:string|null;endDate:string|null}){
 const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[invite,setInvite]=useState("");
 async function action(path:string,method:string,body:unknown){setBusy(true);setError("");try{const r=await fetch(path,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.error);return data;}catch(e){setError(e instanceof Error?e.message:"Não foi possível salvar.");}finally{setBusy(false);}}
 async function edit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const d=await action(`/api/trips/${tripId}`,"PATCH",{title:f.get("title"),description:f.get("description"),start_date:f.get("start_date")||null,end_date:f.get("end_date")||null});if(d)window.location.reload();}
 async function inviteUser(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);const d=await action(`/api/trips/${tripId}/invitations`,"POST",{email:form.get("email"),role:form.get("role")});if(d)setInvite(d.url);}
 return <section className="mt-5 rounded-3xl border bg-white p-5"><h2 className="text-xl font-bold">Gerenciar viagem</h2>{error&&<p role="alert" className="my-3 text-red-700">{error}</p>}<div className="mt-4 flex flex-wrap items-center gap-3"><label>Status <select aria-label="Status da viagem" defaultValue={status} disabled={busy} onChange={async e=>{const d=await action(`/api/trips/${tripId}`,"PATCH",{status:e.target.value});if(d)window.location.reload();}} className="ml-2 rounded-xl border p-3"><option value="planned">Planejada</option><option value="ongoing">Em andamento</option><option value="completed">Concluída</option><option value="archived">Arquivada</option></select></label><button disabled={busy} onClick={async()=>{const d=await action("/api/trips/copy","POST",{trip_id:tripId});if(d)window.location.assign(`/dashboard/trips/${d.trip_id}`);}} className="rounded-xl border p-3">Duplicar roteiro</button></div>
 <form onSubmit={edit} className="mt-5 grid gap-3 sm:grid-cols-2"><input aria-label="Nome da viagem" name="title" required maxLength={120} defaultValue={title} className="rounded-xl border p-3"/><input aria-label="Descrição da viagem" name="description" maxLength={1000} defaultValue={description||""} className="rounded-xl border p-3"/><label>Início<input aria-label="Data de início" name="start_date" type="date" defaultValue={startDate||""} className="ml-2 rounded-xl border p-3"/></label><label>Término<input aria-label="Data de término" name="end_date" type="date" defaultValue={endDate||""} className="ml-2 rounded-xl border p-3"/></label><button disabled={busy} className="rounded-xl border p-3">Salvar viagem</button><button type="button" disabled={busy} onClick={async()=>{if(!confirm("Excluir esta viagem, roteiro, bagagem e arquivos? Esta ação não pode ser desfeita."))return;const d=await action(`/api/trips/${tripId}`,"DELETE",{});if(d)window.location.assign("/dashboard");}} className="rounded-xl border p-3 text-red-700">Excluir viagem</button></form>
 <h3 className="mt-6 font-semibold">Convidar por link privado</h3><p className="mt-1 text-sm text-neutral-500">Válido por 7 dias, somente para o e-mail informado. Copie e envie o link ao participante.</p><form onSubmit={inviteUser} className="mt-3 flex flex-wrap gap-2"><input aria-label="E-mail do convidado" name="email" type="email" required placeholder="E-mail" className="min-w-0 flex-1 rounded-xl border p-3"/><select aria-label="Permissão do convidado" name="role" className="rounded-xl border p-3"><option value="viewer">Visualizador</option><option value="editor">Editor</option></select><button disabled={busy} className="rounded-xl border p-3">Criar convite</button></form>{invite&&<label className="mt-3 block text-sm">Link do convite<input aria-label="Link do convite" readOnly value={invite} onFocus={e=>e.target.select()} className="mt-2 w-full rounded-xl border p-3"/></label>}</section>;
}
