"use client";
import { useEffect,useMemo,useState } from "react";
type Expense={amount:number;currency:string;category?:string;expense_date:string|null}; type Item={completed:boolean}; type Event={status:string;reservation_name:string|null;confirmation_code:string|null;reservation_url:string|null;event_date:string|null;day_index:number;title:string;start_time:string|null;end_time:string|null};
export default function TripSummary({tripId,initialEvents=[]}:{tripId:string;initialEvents?:Event[]}){
 const [expenses,setExpenses]=useState<Expense[]>([]),[items,setItems]=useState<Item[]>([]),[events,setEvents]=useState<Event[]>(initialEvents);
 useEffect(()=>{let active=true;Promise.all([fetch("/api/trips/"+tripId+"/expenses",{cache:"no-store"}).then(r=>r.ok?r.json():null),fetch("/api/trips/"+tripId+"/checklist",{cache:"no-store"}).then(r=>r.ok?r.json():null),]).then(([a,b,c])=>{if(!active)return;if(a?.expenses)setExpenses(a.expenses);if(b?.items)setItems(b.items);if(c?.events)setEvents(c.events)}).catch(()=>{});return()=>{active=false}},[tripId]);
 const expenseBRL=useMemo(()=>expenses.filter(e=>e.currency==="BRL").reduce((s,e)=>s+Number(e.amount),0),[expenses]),checklist=items.length?Math.round(items.filter(i=>i.completed).length/items.length*100):0,completed=events.filter(e=>e.status==="completed").length,reservations=events.filter(e=>e.reservation_name||e.confirmation_code||e.reservation_url).length,activityProgress=events.length?Math.round(completed/events.length*100):0;
 const dayStats=useMemo(()=>{const map=new Map<number,{count:number;completed:number;reservations:number}>();for(const e of events){const day=e.day_index||1;const current=map.get(day)||{count:0,completed:0,reservations:0};current.count++;if(e.status==="completed")current.completed++;if(e.reservation_name||e.confirmation_code||e.reservation_url)current.reservations++;map.set(day,current)}return [...map.entries()].sort((a,b)=>a[0]-b[0])},[events]);
 const stats=[["Atividades",events.length],["Concluídas",completed],["Reservas",reservations],["Checklist",checklist+"%"],["Gastos BRL",expenseBRL.toLocaleString("pt-BR",{style:"currency",currency:"BRL"})],["Itens",items.length]];
 return <section className="mt-7 rounded-3xl border border-neutral-200 bg-white p-6 shadow-sm"><div><p className="text-xs font-bold uppercase tracking-widest text-neutral-400">Visão geral</p><h2 className="mt-1 text-xl font-bold text-neutral-950">Resumo da viagem</h2><p className="mt-1 text-sm text-neutral-500">Uma visão rápida do andamento do planejamento.</p></div><div className="mt-5 grid grid-cols-2 gap-3 md:grid-cols-4 lg:grid-cols-6">{stats.map(([label,value])=><div key={String(label)} className="rounded-2xl border border-neutral-200 bg-neutral-50 p-4 transition-colors"><p className="text-xs text-neutral-500">{label}</p><strong className="mt-1 block text-lg text-neutral-950">{value}</strong></div>)}</div><div className="mt-6 grid gap-4 md:grid-cols-2">{[["Progresso do itinerário",activityProgress],["Checklist",checklist]].map(([label,value])=><div key={String(label)} className="rounded-2xl border border-neutral-200 bg-neutral-50 p-4"><div className="flex justify-between text-xs font-semibold text-neutral-600"><span>{label}</span><span>{value}%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-neutral-200"><div className="h-full rounded-full bg-neutral-950 transition-all" style={{width:value+"%"}}/></div></div>)}</div><div className="mt-6"><p className="text-sm font-bold text-neutral-900">Ritmo por dia</p><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{dayStats.map(([day,data])=><div key={day} className="rounded-2xl border border-neutral-200 bg-neutral-50 p-3"><div className="flex items-center justify-between"><span className="text-sm font-semibold">Dia {day}</span><span className="text-xs text-neutral-500">{data.count} atividade{data.count===1?"":"s"}</span></div><div className="mt-2 flex flex-wrap gap-2 text-xs text-neutral-500"><span>{data.completed} concluída{data.completed===1?"":"s"}</span><span>·</span><span>{data.reservations} reserva{data.reservations===1?"":"s"}</span></div></div>)}</div></div></section>;
}