"use client";

import { useEffect, useMemo, useState } from "react";

type Expense={id:string;title:string;category:string;amount:number;currency:string;expense_date:string|null;notes:string|null};
type Item={id:string;title:string;category:string;completed:boolean};
type TripMeta={budget_amount:number|null;budget_currency:string};

export default function TripTools({tripId,canEdit=true}:{tripId:string;canEdit?:boolean}){
 const [expenses,setExpenses]=useState<Expense[]>([]); const [items,setItems]=useState<Item[]>([]);
 const [expense,setExpense]=useState({title:"",category:"other",amount:"",currency:"BRL",expense_date:"",notes:""}); const [budget,setBudget]=useState(""); const [budgetCurrency,setBudgetCurrency]=useState("BRL"); const [budgetSaving,setBudgetSaving]=useState(false);
 const [item,setItem]=useState({title:"",category:"general"}); const [message,setMessage]=useState("");
 const totalByCurrency=useMemo(()=>expenses.reduce<Record<string,number>>((acc,e)=>{const key=(e.currency||"BRL").toUpperCase();acc[key]=(acc[key]||0)+Number(e.amount);return acc;},{}),[expenses]);
 const categories=useMemo(()=>Object.entries(expenses.reduce<Record<string,number>>((acc,e)=>{const key=e.category||"other";acc[key]=(acc[key]||0)+Number(e.amount);return acc;},{})).sort((a,b)=>b[1]-a[1]),[expenses]);
 const total=totalByCurrency[expense.currency]||0;
 const budgetValue=Number(budget); const budgetProgress=budgetValue>0?Math.min(100,Math.round(total/budgetValue*100)):0;
 const completedItems=useMemo(()=>items.filter(i=>i.completed).length,[items]);
 const checklistProgress=items.length?Math.round(completedItems/items.length*100):0;
 async function load(){const[a,b,t]=await Promise.all([fetch("/api/trips/"+tripId+"/expenses"),fetch("/api/trips/"+tripId+"/checklist"),fetch("/api/trips/"+tripId)]);if(a.ok)setExpenses((await a.json()).expenses);if(b.ok)setItems((await b.json()).items);if(t.ok){const data=await t.json();const meta={budget_amount:data.trip?.budget_amount??null,budget_currency:data.trip?.budget_currency||"BRL"};setBudget(meta.budget_amount==null?"":String(meta.budget_amount));setBudgetCurrency(meta.budget_currency);}}
 useEffect(()=>{load()},[]);
 async function addExpense(e:React.FormEvent){e.preventDefault();const r=await fetch("/api/trips/"+tripId+"/expenses",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(expense)});const d=await r.json();if(!r.ok){setMessage(d.error||"Erro ao adicionar despesa.");return;}setExpenses(x=>[d.expense,...x]);setExpense({title:"",category:"other",amount:"",currency:"BRL",expense_date:"",notes:""});}
 async function addItem(e:React.FormEvent){e.preventDefault();const r=await fetch("/api/trips/"+tripId+"/checklist",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(item)});const d=await r.json();if(!r.ok){setMessage(d.error||"Erro ao adicionar item.");return;}setItems(x=>[...x,d.item]);setItem({title:"",category:"general"});}
 async function toggle(i:Item){const r=await fetch("/api/trips/"+tripId+"/checklist?itemId="+i.id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({completed:!i.completed})});const d=await r.json();if(r.ok)setItems(x=>x.map(v=>v.id===i.id?d.item:v));}
 async function removeExpense(id:string){const r=await fetch("/api/trips/"+tripId+"/expenses?expenseId="+id,{method:"DELETE"});if(r.ok)setExpenses(x=>x.filter(v=>v.id!==id));}
 async function removeItem(id:string){const r=await fetch("/api/trips/"+tripId+"/checklist?itemId="+id,{method:"DELETE"});if(r.ok)setItems(x=>x.filter(v=>v.id!==id));}
 async function saveBudget(e:React.FormEvent){e.preventDefault();setBudgetSaving(true);const current=await fetch("/api/trips/"+tripId);const currentData=await current.json();const r=await fetch("/api/trips/"+tripId,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:currentData.trip?.title||"Viagem",description:currentData.trip?.description||"",start_date:currentData.trip?.start_date||null,end_date:currentData.trip?.end_date||null,budget_amount:budget===""?null:Number(budget),budget_currency:budgetCurrency})});const d=await r.json();if(!r.ok){setMessage(d.error||"Não foi possível salvar o orçamento.");}else{setMessage("Orçamento atualizado.");}setBudgetSaving(false);}
 return <section className="mt-7 grid gap-7 lg:grid-cols-2">
  <div className="rounded-3xl border border-neutral-200 bg-white p-6 shadow-sm lg:col-span-2"><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><h2 className="text-xl font-bold">Orçamento</h2><p className="text-sm text-neutral-500">Acompanhe o gasto real e compare com o limite planejado.</p></div>{canEdit&&<form onSubmit={saveBudget} className="flex flex-wrap gap-2"><input type="number" min="0" step="0.01" value={budget} onChange={e=>setBudget(e.target.value)} placeholder="Orçamento" className="w-36 rounded-xl border p-2.5"/><input value={budgetCurrency} onChange={e=>setBudgetCurrency(e.target.value.toUpperCase())} maxLength={8} className="w-20 rounded-xl border p-2.5" /><button disabled={budgetSaving} className="rounded-xl bg-neutral-950 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{budgetSaving?"Salvando...":"Salvar"}</button></form>}</div><div className="mt-5 grid gap-3 sm:grid-cols-3">{Object.entries(totalByCurrency).map(([currency,value])=><div key={currency} className="rounded-2xl bg-neutral-50 p-4"><p className="text-xs text-neutral-500">Gasto em {currency}</p><strong className="mt-1 block text-lg">{value.toLocaleString("pt-BR",{minimumFractionDigits:2})} {currency}</strong></div>)}{!Object.keys(totalByCurrency).length&&<div className="rounded-2xl bg-neutral-50 p-4 text-sm text-neutral-500">Nenhum gasto registrado.</div>}</div>{budgetValue>0&&<div className="mt-5"><div className="flex justify-between text-xs font-semibold"><span>Orçamento em {budgetCurrency}</span><span>{budgetSpent} / {budgetValue}</span></div><div className="mt-2 h-3 overflow-hidden rounded-full bg-neutral-100"><div className="h-full bg-neutral-950 transition-all" style={{width:budgetProgress+"%"}}/></div><p className="mt-2 text-xs text-neutral-500">{budgetProgress}% utilizado · restante {Math.max(0,budgetValue-budgetSpent).toLocaleString("pt-BR",{minimumFractionDigits:2})} {budgetCurrency}</p></div>}<div className="mt-5 flex flex-wrap gap-2">{categories.map(([category,value])=><span key={category} className="rounded-full border px-3 py-1.5 text-xs font-semibold">{category}: {value.toFixed(2)}</span>)}</div></div>
  <div className="rounded-3xl border border-neutral-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="text-xl font-bold">Gastos</h2><p className="text-sm text-neutral-500">Controle despesas por categoria e moeda.</p></div><strong>{total.toFixed(2)} {expense.currency}</strong></div>
   {canEdit && <form onSubmit={addExpense} className="mt-5 grid gap-2 sm:grid-cols-2"><input required placeholder="Descrição" value={expense.title} onChange={e=>setExpense({...expense,title:e.target.value})} className="rounded-xl border p-2.5 sm:col-span-2"/><input required type="number" min="0" step="0.01" placeholder="Valor" value={expense.amount} onChange={e=>setExpense({...expense,amount:e.target.value})} className="rounded-xl border p-2.5"/><select value={expense.category} onChange={e=>setExpense({...expense,category:e.target.value})} className="rounded-xl border p-2.5"><option value="transport">Transporte</option><option value="food">Alimentação</option><option value="lodging">Hospedagem</option><option value="tickets">Ingressos</option><option value="shopping">Compras</option><option value="other">Outros</option></select><input value={expense.currency} onChange={e=>setExpense({...expense,currency:e.target.value.toUpperCase()})} maxLength={8} className="rounded-xl border p-2.5" placeholder="BRL"/><input type="date" value={expense.expense_date} onChange={e=>setExpense({...expense,expense_date:e.target.value})} className="rounded-xl border p-2.5"/><button className="rounded-xl bg-neutral-950 p-2.5 font-semibold text-white sm:col-span-2">Adicionar gasto</button></form>}
   <div className="mt-5 space-y-2">{expenses.map(e=><div key={e.id} className="flex items-center justify-between rounded-xl bg-neutral-50 p-3"><div><b>{e.title}</b><p className="text-xs text-neutral-500">{e.category} · {e.expense_date||"sem data"}</p></div><div className="flex items-center gap-3"><span className="font-semibold">{Number(e.amount).toFixed(2)} {e.currency}</span>{canEdit && <button onClick={()=>removeExpense(e.id)} className="text-xs text-red-600">Remover</button>}</div></div>)}</div>
  </div>
  <div className="rounded-3xl border border-neutral-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Checklist</h2><p className="text-sm text-neutral-500">Coisas para fazer ou levar nesta viagem.</p>
   {canEdit && <form onSubmit={addItem} className="mt-5 flex gap-2"><input required placeholder="Ex.: Passaporte" value={item.title} onChange={e=>setItem({...item,title:e.target.value})} className="min-w-0 flex-1 rounded-xl border p-2.5"/><button className="rounded-xl bg-neutral-950 px-4 font-semibold text-white">Adicionar</button></form>}
   <div className="mt-4 h-2 overflow-hidden rounded-full bg-neutral-100"><div className="h-full bg-neutral-950 transition-all" style={{width:checklistProgress+"%"}} /></div><p className="mt-2 text-xs text-neutral-500">{completedItems} de {items.length} concluídos · {checklistProgress}%</p><div className="mt-5 space-y-2">{items.map(i=><div key={i.id} className="flex items-center gap-3 rounded-xl bg-neutral-50 p-3"><input type="checkbox" checked={i.completed} disabled={!canEdit} onChange={()=>toggle(i)} className="h-4 w-4"/><span className={i.completed?"flex-1 text-sm text-neutral-400 line-through":"flex-1 text-sm"}>{i.title}</span>{canEdit && <button onClick={()=>removeItem(i.id)} className="text-xs text-red-600">Remover</button>}</div>)}</div>
  </div>
  {message&&<p className="text-sm text-red-600 lg:col-span-2">{message}</p>}
 </section>
}
