"use client";
import { useCallback, useEffect, useState, type FormEvent } from "react";
type Item = { id: string; name: string; quantity: number; status: string; category: string | null; notes: string | null };
type List = { id: string; name: string; items: Item[] };
export default function TripPacking({ tripId, canEdit }: { tripId: string; canEdit: boolean }) {
 const [lists,setLists] = useState<List[]>([]); const [error,setError] = useState(""); const [busy,setBusy] = useState(false); const [loading,setLoading] = useState(true); const [pending,setPending] = useState(false);
 const [templates,setTemplates] = useState<{id:string;name:string}[]>([]);
 const [editing,setEditing] = useState<Item | null>(null);
 const endpoint = `/api/trips/${tripId}/packing`;
 const load = useCallback(async () => { try { const r = await fetch(endpoint); const data = await r.json(); if (!r.ok) throw new Error(data.error); setLists(data.lists); setTemplates(data.templates || []); } catch { setError("Não foi possível carregar a bagagem."); } finally { setLoading(false); } }, [endpoint]);
 useEffect(() => { void load(); }, [load]);
 async function mutate(method: string, body?: unknown, suffix = "") {
  setBusy(true);setError("");
  try { const r = await fetch(endpoint+suffix,{ method,headers:{"Content-Type":"application/json"},body:body ? JSON.stringify(body) : undefined }); const data = await r.json(); if (!r.ok) throw new Error(data.error); await load(); return true; }
  catch(err) { setError(err instanceof Error ? err.message : "Não foi possível salvar."); return false; } finally { setBusy(false); }
 }
 async function add(event: FormEvent<HTMLFormElement>, listId?: string) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); if(await mutate("POST",{name:data.get("name"),quantity:data.get("quantity") || 1,list_id:listId}))form.reset(); }
 const all = lists.flatMap(list=>list.items); const packed = all.filter(item=>item.status==="packed").length;
 return <section className="mt-5 rounded-3xl border bg-white p-5 sm:p-7"><h2 className="text-xl font-bold">Bagagem</h2><p className="mt-2 text-sm text-neutral-500">{packed} de {all.length} itens guardados</p><progress className="mt-3 w-full" aria-label="Progresso da bagagem" max={all.length || 1} value={packed}/>
 {error && <p role="alert" className="my-3 text-red-700">{error}</p>}{loading && <p role="status">Carregando bagagem…</p>}
 <label className="my-3 flex gap-2 text-sm"><input type="checkbox" checked={pending} onChange={e=>setPending(e.target.checked)}/>Mostrar apenas itens não guardados</label>
 {!loading && !lists.length && <p className="my-4 text-neutral-500">Crie uma mala ou mochila para organizar seus itens.</p>}
 {canEdit && <form onSubmit={e=>add(e)} className="my-4 flex flex-wrap gap-2"><input aria-label="Nome da lista" name="name" required maxLength={120} placeholder="Mala principal" className="min-w-0 flex-1 rounded-xl border p-3"/><button disabled={busy} className="rounded-xl bg-neutral-950 p-3 text-white">Criar lista</button></form>}
 {canEdit && templates.length > 0 && <details className="my-4 rounded-xl border p-3"><summary className="cursor-pointer font-semibold">Meus modelos de bagagem</summary><p className="my-2 text-sm text-neutral-500">Crie uma lista com os itens do modelo. Todos começam como pendentes.</p>{templates.map(template=><div key={template.id} className="flex flex-wrap items-center gap-3 py-2"><span className="flex-1">{template.name}</span><button disabled={busy} onClick={()=>void mutate("POST",{name:template.name,template_id:template.id})} className="rounded-lg border p-2">Usar modelo</button><button disabled={busy} onClick={()=>{if(confirm("Excluir este modelo? As listas já criadas serão mantidas."))void mutate("DELETE",undefined,`?kind=template&itemId=${template.id}`);}} className="p-2 text-red-700">Excluir</button></div>)}</details>}
 <div className="grid gap-4 sm:grid-cols-2">{lists.map(list=><article key={list.id} className="rounded-2xl border p-4"><h3 className="font-semibold">{list.name}</h3>
 {list.items.filter(item=>!pending||item.status!=="packed").map(item=><div key={item.id} className="my-3 flex flex-wrap items-center gap-2"><span className="flex-1">{item.quantity} × {item.name}{item.category && <small className="block text-neutral-500">{item.category}</small>}{item.notes && <small className="block whitespace-pre-wrap text-neutral-500">{item.notes}</small>}</span><select aria-label={`Status de ${item.name}`} value={item.status} disabled={!canEdit||busy} onChange={e=>void mutate("PATCH",{id:item.id,status:e.target.value})} className="rounded-lg border p-2"><option value="pending">Pendente</option><option value="prepared">Separado</option><option value="packed">Guardado</option></select>{canEdit&&<button disabled={busy} onClick={()=>setEditing({...item,category:item.category || "",notes:item.notes || ""})} className="p-2">Editar</button>}{canEdit&&<button disabled={busy} aria-label={`Excluir ${item.name}`} onClick={()=>{if(confirm("Excluir este item?"))void mutate("DELETE",undefined,`?itemId=${item.id}`);}} className="p-2 text-red-700">Excluir</button>}</div>)}
 {canEdit && editing && list.items.some(item=>item.id===editing.id) && <form className="my-4 grid gap-2 rounded-xl border p-3" onSubmit={async event=>{event.preventDefault();if(await mutate("PATCH",editing))setEditing(null);}}>
 <label className="text-sm">Nome<input required maxLength={120} value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})} className="block w-full rounded-lg border p-2"/></label>
 <label className="text-sm">Quantidade<input required type="number" min={1} max={999} value={editing.quantity} onChange={e=>setEditing({...editing,quantity:Number(e.target.value)})} className="block w-full rounded-lg border p-2"/></label>
 <label className="text-sm">Categoria<input maxLength={80} value={editing.category || ""} onChange={e=>setEditing({...editing,category:e.target.value})} className="block w-full rounded-lg border p-2"/></label>
 <label className="text-sm">Observações<textarea maxLength={1000} value={editing.notes || ""} onChange={e=>setEditing({...editing,notes:e.target.value})} className="block w-full rounded-lg border p-2"/></label>
 <div className="flex gap-3"><button disabled={busy} className="rounded-lg bg-neutral-950 p-2 text-white">Salvar item</button><button type="button" disabled={busy} onClick={()=>setEditing(null)}>Cancelar</button></div></form>}
 {canEdit&&<><form onSubmit={e=>add(e,list.id)} className="mt-4 flex flex-wrap gap-2"><input aria-label={`Novo item em ${list.name}`} name="name" required maxLength={120} placeholder="Novo item" className="min-w-0 flex-1 rounded-lg border p-2"/><input aria-label="Quantidade" name="quantity" type="number" min={1} max={999} defaultValue={1} className="w-16 rounded-lg border p-2"/><button disabled={busy} className="rounded-lg border p-2">Adicionar</button></form><div className="mt-3 flex flex-wrap gap-4"><button disabled={busy} onClick={()=>void mutate("POST",{name:list.name,save_template:list.id})} className="py-2 text-sm">Salvar como modelo</button><button disabled={busy} onClick={()=>void mutate("POST",{name:`${list.name} (cópia)`,duplicate_id:list.id})} className="py-2 text-sm">Duplicar lista</button><button disabled={busy} onClick={()=>{if(confirm("Excluir a lista e seus itens?"))void mutate("DELETE",undefined,`?kind=list&itemId=${list.id}`);}} className="py-2 text-sm text-red-700">Excluir lista</button></div></>}
 </article>)}</div></section>;
}
