"use client";
import { useEffect,useMemo,useState } from "react";
type Reservation={id:string;title:string;event_date:string|null;start_time:string|null;end_time:string|null;reservation_name:string|null;confirmation_code:string|null;reservation_url:string|null;reminder_minutes:number|null;day_index:number};
export default function TripReservations({tripId}:{tripId:string}){
 const[items,setItems]=useState<Reservation[]>([]),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);const r=await fetch("/api/trips/"+tripId+"/events",{cache:"no-store"});if(r.ok){const d=await r.json();setItems((d.events||[]).filter((e:Reservation)=>e.reservation_name||e.confirmation_code||e.reservation_url))}setLoading(false)}
 useEffect(()=>{void load()},[tripId]);
 const sorted=useMemo(()=>[...items].sort((a,b)=>a.day_index-b.day_index||(a.event_date||"").localeCompare(b.event_date||"")||(a.start_time||"").localeCompare(b.start_time||"")),[items]);
 return <section className="mt-5 rounded-3xl border border-neutral-200 bg-white p-4 shadow-sm sm:mt-7 sm:p-6">
  <div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div className="min-w-0"><p className="text-xs font-bold uppercase tracking-widest text-neutral-400">Documentos</p><h2 className="mt-1 text-xl font-bold text-neutral-950">Reservas</h2><p className="mt-1 text-sm text-neutral-500">Hotéis, voos, restaurantes, ingressos e outras reservas do roteiro.</p></div><span className="self-start rounded-full border border-neutral-200 bg-neutral-50 px-3 py-1.5 text-xs font-semibold text-neutral-600 sm:self-auto">{items.length} {items.length===1?"reserva":"reservas"}</span></div>
  {loading?<p className="mt-5 text-sm text-neutral-500">Carregando reservas...</p>:sorted.length===0?<p className="mt-5 rounded-2xl border border-dashed border-neutral-200 bg-neutral-50 p-5 text-sm text-neutral-500">Nenhuma reserva cadastrada. Preencha os dados de reserva ao criar uma atividade.</p>:<div className="mt-5 grid gap-3 md:grid-cols-2">{sorted.map(item=><article key={item.id} className="rounded-2xl border border-neutral-200 bg-neutral-50 p-4">
    <div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><p className="text-xs font-bold uppercase tracking-wider text-neutral-400">Dia {item.day_index}</p><h3 className="mt-1 break-words font-bold text-neutral-950">{item.reservation_name||item.title}</h3><p className="mt-1 break-words text-xs text-neutral-500">{item.event_date||"Data não definida"}{item.start_time?" · "+item.start_time:""}{item.end_time?"–"+item.end_time:""}</p></div>{item.reminder_minutes!=null&&<span className="self-start whitespace-nowrap rounded-full border border-neutral-200 bg-white px-2 py-1 text-[11px] font-semibold text-neutral-600">{item.reminder_minutes} min antes</span>}</div>
    {item.confirmation_code&&<div className="mt-3 rounded-xl border border-neutral-200 bg-white p-3"><p className="text-[11px] uppercase tracking-wider text-neutral-400">Código</p><p className="mt-1 break-all font-mono font-semibold text-neutral-900">{item.confirmation_code}</p></div>}
    {item.reservation_url&&<a href={item.reservation_url} target="_blank" rel="noreferrer" className="mt-3 inline-flex min-h-10 items-center rounded-xl bg-neutral-950 px-3 py-2 text-xs font-semibold text-white transition-opacity hover:opacity-80">Abrir reserva</a>}
  </article>)}</div>}
 </section>;
}