import Link from "next/link";
import Image from "next/image";
import { ArrowDown, ArrowRight, ArrowUpRight, Check, Compass, MapPin, Route, Luggage, Wallet, BookOpen, Globe2 } from "lucide-react";
import styles from "./landing.module.css";

const features = [
 {icon:Route,number:"01",title:"Um roteiro com a sua cara.",text:"Organize lugares e atividades por dia. Veja o caminho no mapa e deixe espaço para o inesperado."},
 {icon:Luggage,number:"02",title:"Leve só o que importa.",text:"Monte suas malas, prepare o checklist e guarde os documentos da viagem no mesmo lugar."},
 {icon:Wallet,number:"03",title:"Os gastos, sem surpresas.",text:"Defina seu orçamento e acompanhe as despesas de cada viagem, separadas por moeda."},
];
export default function Home(){return <main className={styles.page}>
 <a href="#conteudo" className="nbg-skip-link">Pular para o conteúdo</a>
 <header className={styles.header}><Link href="/" className={styles.brand} aria-label="NaBagagem, página inicial"><Compass aria-hidden="true" size={29}/><span>NaBagagem<span className={styles.brandDot}>.</span></span></Link><nav className={styles.nav} aria-label="Navegação principal"><a href="#como-funciona">Como funciona</a><a href="#descubra">Inspire-se</a></nav><div className={styles.headerActions}><Link href="/login">Entrar</Link><Link className={styles.smallButton} href="/cadastro">Criar conta <ArrowUpRight size={15} aria-hidden="true"/></Link></div></header>
 <section id="conteudo" className={styles.hero}><div className={styles.heroCopy}><p className={styles.eyebrow}><span/> PARA QUEM TEM O MUNDO NOS PLANOS</p><h1>A próxima história<br/> começa <em>na bagagem.</em></h1><p className={styles.lead}>Do primeiro “vamos?” à última lembrança.<br className={styles.desktopBreak}/> Planeje, organize e guarde suas viagens em um só lugar.</p><div className={styles.heroActions}><Link href="/cadastro" className={styles.button}>Planejar minha viagem <ArrowUpRight size={19} aria-hidden="true"/></Link><a href="#como-funciona" className={styles.textLink}>Conhecer o NaBagagem <ArrowDown size={16} aria-hidden="true"/></a></div><p className={styles.heroNote}><Check size={14} aria-hidden="true"/> Roteiro, bagagem e memórias. Tudo junto.</p></div>
 <div className={styles.heroVisual}><div className={styles.photoFrame}><Image src="/images/lake-journey.jpg" alt="Vista de um barco de madeira em um lago cercado por montanhas" fill priority sizes="(max-width: 800px) 100vw, 50vw" className={styles.heroImage}/><div className={styles.photoShade}/><span className={styles.photoTag}><MapPin size={13} aria-hidden="true"/> UM DESTINO. MIL POSSIBILIDADES.</span><div className={styles.photoCaption}><span>Vá onde você<br/>se sente vivo.</span><ArrowUpRight size={36} aria-hidden="true"/></div></div><div className={styles.routeCard}><div className={styles.routeIcon}><Route size={21} aria-hidden="true"/></div><div><small>SEU PRÓXIMO ROTEIRO</small><strong>Um dia de cada vez.</strong><span>Planejado por você. Vivido do seu jeito.</span></div><Check size={17} aria-hidden="true"/></div><div className={styles.stamp} aria-hidden="true"><Globe2 size={23}/><span>COLECIONE<br/>CAMINHOS</span></div></div></section>
 <div className={styles.ribbon}><span>ANTES, DURANTE E DEPOIS.</span><span><Route size={17} aria-hidden="true"/> Roteiros</span><span><Luggage size={17} aria-hidden="true"/> Bagagem</span><span><Wallet size={17} aria-hidden="true"/> Gastos</span><span><BookOpen size={17} aria-hidden="true"/> Memórias</span></div>
 <section id="como-funciona" className={styles.features}><div className={styles.sectionHead}><div><p className={styles.eyebrow}>MENOS ABAS ABERTAS. MAIS MUNDO.</p><h2>Uma viagem inteira.<br/><em>Um lugar para organizar.</em></h2></div><p>Passagens aqui, reservas ali, uma lista perdida nas notas. Reúna os detalhes e aproveite o que realmente fez você sair de casa.</p></div><div className={styles.featureGrid}>{features.map(({icon:Icon,number,title,text})=><article key={number} className={styles.feature}><div className={styles.featureTop}><Icon size={25} strokeWidth={1.5} aria-hidden="true"/><span>{number}</span></div><h3>{title}</h3><p>{text}</p></article>)}</div></section>
 <section className={styles.planner}><div className={styles.plannerCopy}><p className={styles.eyebrow}>DA IDEIA AO ITINERÁRIO</p><h2>O melhor plano<br/>é <em>o seu.</em></h2><p>Uma manhã sem pressa. Aquele café que você salvou. Um desvio que vale a pena. Dê um lugar para cada ideia no seu roteiro.</p><ul><li><Check size={17} aria-hidden="true"/> Destinos e atividades organizados por dia</li><li><Check size={17} aria-hidden="true"/> Convites para planejar com sua companhia</li><li><Check size={17} aria-hidden="true"/> Fotos e documentos junto da viagem</li></ul><Link href="/cadastro" className={styles.textLink}>Tirar uma viagem do papel <ArrowRight size={17} aria-hidden="true"/></Link></div><div className={styles.itinerary}><div className={styles.itineraryTop}><span>MEU ROTEIRO</span><small>Exemplo de planejamento</small></div><div className={styles.itineraryTitle}><div><h3>Uma semana no Japão</h3><p><MapPin size={13} aria-hidden="true"/> Kyoto · Nara · Tokyo</p></div><span className={styles.tripBadge}>7 dias</span></div><div className={styles.days}><span>Dia 01</span><span>Dia 02</span><span>Dia 03</span><span>Dia 04</span></div><div className={styles.timeline}>{[{time:"09:00",title:"Uma manhã em Higashiyama",detail:"Caminhar, explorar e se perder um pouco."},{time:"12:30",title:"Pausa para um ramen",detail:"Um sabor novo também é uma lembrança."},{time:"16:00",title:"O pôr do sol no templo",detail:"O último compromisso: aproveitar."}].map((item,i)=><div className={styles.timelineItem} key={item.time}><time>{item.time}</time><span className={styles.timelineDot}>{i+1}</span><div><strong>{item.title}</strong><p>{item.detail}</p></div></div>)}</div><div className={styles.itineraryBottom}><Check size={14} aria-hidden="true"/> Espaço para os planos. E para mudar de ideia.</div></div></section>
 <section id="descubra" className={styles.discovery}><div className={styles.discoveryPhoto}><Image src="/images/kyoto-journey.jpg" alt="Rua tradicional de Kyoto com um pagode ao fundo" fill sizes="(max-width: 800px) 100vw, 50vw"/><span><MapPin size={14} aria-hidden="true"/> Kyoto, Japão</span></div><div className={styles.discoveryCopy}><p className={styles.eyebrow}>O MUNDO CONTINUA CHAMANDO</p><h2>Seu próximo destino<br/>pode começar com<br/><em>uma boa história.</em></h2><p>Explore roteiros públicos, descubra lugares por outros olhares e encontre inspiração para a viagem que ainda vem.</p><Link className={styles.button} href="/descoberta">Explorar destinos <ArrowUpRight size={18} aria-hidden="true"/></Link></div></section>
 <section className={styles.finalCta}><Compass size={35} strokeWidth={1.3} aria-hidden="true"/><p className={styles.eyebrow}>BORA COLOCAR O PÉ NA ESTRADA?</p><h2>Tem muita vida<br/><em>lá fora.</em></h2><Link href="/cadastro" className={styles.lightButton}>Começar minha próxima história <ArrowUpRight size={18} aria-hidden="true"/></Link><p>Você escolhe o destino. A gente ajuda com os detalhes.</p></section>
 <footer className={styles.footer}><Link href="/" className={styles.brand}><Compass size={23} aria-hidden="true"/>NaBagagem.</Link><p>Planeje. Viva. Guarde.</p><div><Link href="/login">Entrar</Link><Link href="/cadastro">Criar conta</Link><a href="#conteudo">Voltar ao topo ↑</a></div></footer>
 </main>}
