"use client";
import {useEffect,useState,type FormEvent} from "react";
import {createAuthClient} from "@neondatabase/auth/next";
import {browserLocale,dictionaries,type Locale} from "@/lib/i18n/dictionaries";
export default function AccountPreferences(){
 const[locale,setLocale]=useState<Locale>("pt-BR");const[currency,setCurrency]=useState("BRL");const[moderation,setModeration]=useState(true);const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);const[ready,setReady]=useState(false);const t=dictionaries[locale];
 useEffect(()=>{setLocale(browserLocale());fetch("/api/profile/preferences").then(async r=>{if(!r.ok)throw new Error();return r.json();}).then(d=>{setLocale(d.locale);setCurrency(d.currency);setModeration(d.moderate_comments);setReady(true);}).catch(()=>setMessage("Não foi possível carregar suas preferências."));},[]);
 async function save(e:FormEvent){e.preventDefault();setBusy(true);try{const r=await fetch("/api/profile/preferences",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({locale,currency,moderate_comments:moderation})});setMessage(r.ok?t.saved:t.failed);if(r.ok)window.dispatchEvent(new Event("nabagagem-locale"));}catch{setMessage(t.failed);}finally{setBusy(false);}}
 async function password(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const data=new FormData(form);setBusy(true);try{const auth=createAuthClient();const r=await auth.changePassword({currentPassword:String(data.get("current")),newPassword:String(data.get("next")),revokeOtherSessions:true});setMessage(r.error?"Não foi possível alterar a senha. Confira a senha atual.":"Senha alterada. Outras sessões foram encerradas.");if(!r.error)form.reset();}catch{setMessage("Não foi possível alterar a senha.");}finally{setBusy(false);}}
 return <section className="rounded-3xl border bg-white p-6"><h2 className="font-bold">{t.preferences}</h2>{message&&<p role="status" className="my-3">{message}</p>}<form onSubmit={save} className="mt-4 space-y-4"><label className="block">{t.language}<select value={locale} onChange={e=>setLocale(e.target.value as Locale)} className="ml-3 rounded-xl border p-3"><option value="pt-BR">Português</option><option value="en">English</option><option value="ja">日本語</option></select></label><label className="block">{t.currency}<input value={currency} onChange={e=>setCurrency(e.target.value.toUpperCase())} pattern="[A-Z]{3}" maxLength={3} required className="ml-3 w-24 rounded-xl border p-3"/></label><label className="flex gap-2"><input type="checkbox" checked={moderation} onChange={e=>setModeration(e.target.checked)}/>{t.moderation}</label><button disabled={busy||!ready} className="rounded-xl bg-neutral-950 p-3 text-white">{t.save}</button></form><a href="/api/profile/export" className="mt-5 block underline">{t.export}</a>
 <form onSubmit={password} className="mt-6 grid gap-3"><h3 className="font-semibold">Alterar senha</h3><input aria-label="Senha atual" type="password" name="current" autoComplete="current-password" required className="rounded-xl border p-3" placeholder="Senha atual"/><input aria-label="Nova senha" type="password" name="next" autoComplete="new-password" minLength={8} required className="rounded-xl border p-3" placeholder="Nova senha (mínimo 8 caracteres)"/><button disabled={busy} className="rounded-xl border p-3">Alterar senha</button></form><form action="/api/auth/logout" method="post" className="mt-5"><button className="rounded-xl border p-3">{t.logout}</button></form></section>;
}
